all: false
force-file-write: false
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: 'main'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/docker/docker/client:
    config:
      dir: './cmd/docker-stat'
      filename: mocks_test.go
    interfaces:
      ContainerAPIClient:
