all: false
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: 'main'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/docker/docker/client:
    config:
      dir: './cmd/docker-stat'
      filename: mocks_test.go
    interfaces:
      ContainerAPIClient:
  github.com/mitchellh/go-ps:
    config:
      dir: './cmd/proc-stat'
      filename: ps-mocks_test.go
      structname: '{{.Mock}}Ps{{.InterfaceName}}'
    interfaces:
      Process:
  github.com/aknopov/perform/cmd/param:
    config:
      dir: './cmd/proc-stat'
      filename: q-mocks_test.go
      structname: '{{.Mock}}Q{{.InterfaceName}}'
    interfaces:
      IQProcess:
